import FunctionPackage as funp;
funp.extendtuple([2,3,4,5],(1,6,7,8))
funp.add(12,36)
funp.sub(36,12)
funp.mul(12,36)
funp.div(36,12)
num = float(input('Enter a number: '))
funp.sqrt(num)
funp.substr("Pack: My: Box: With: Good: Food",":")
f=input("enter number")
s=input("enter number")
t=input("enter number")
fou=input("enter number")
funp.findmax(first=f,second=s,third=t,fourth=fou)
var1 = raw_input("Enter a string: ")
funp.chkpalindrome(var=var1)
funp.findvalue(1,2)
count=input("Enter count number to print")
funp.fib(count)